import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/styles/shared-globals.css";
import { MicrosoftClarity, AnalyticsWrapper } from "@repo/analytics/components";
import { ThemeProvider } from "@/lib/theme-provider";
import { TrpcProvider } from "@/lib/trpc-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Template Turbo Repo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <MicrosoftClarity />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
          enableSystem>
          <TrpcProvider>
            <AnalyticsWrapper>{children}</AnalyticsWrapper>
          </TrpcProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
